project:
  type: website
  render:
    - index.qmd
    - pages/writing/index.qmd
    - pages/sharing/index.qmd
    - pages/optimizing/index.qmd
    - pages/vibing/index.qmd
    - pages/further/index.qmd

engines: ['julia']

website:
  title: "MoMoJuWo"
  llms-txt: true
  navbar:
    left:
      - pages/writing/index.qmd
      - pages/sharing/index.qmd
      - pages/optimizing/index.qmd
      - pages/vibing/index.qmd
      - pages/further/index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



